parameters:
#    bundle_hello_world.example.class: Bundle\HelloWorldBundle\Example

services:
#    bundle_hello_world.example:
#        class: %bundle_hello_world.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
